### ISSUE TITLE
android dlopen failed: cannot locate symbol 

### ISSUE THREAD

**Issue by waterbang** [denoland/rusty_v8#1170]
I compiled `librusty_v8_release_aarch64-linux-android.a` in `rusty_v8`, and then compiled a dynamic link library in my rust project to use in `android`.

But the following error occurs.

```
 java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZNK2v811ArrayBuffer11WasDetachedEv" referenced by "/data/app/~~dol7RO1FL1IHanVBeCAb7g==/info.bagen.rust.plaoc-U3apDfKhRbuGwny_Uw1B5A==/base.apk!/lib/arm64-v8a/librust_lib.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
        at java.lang.Runtime.loadLibrary0(Runtime.java:998)
        at java.lang.System.loadLibrary(System.java:1656)
        at info.bagen.rust.plaoc.DenoService.<clinit>(DenoService.kt:44)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
        at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:75)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4922)
        at android.app.ActivityThread.access$1900(ActivityThread.java:310)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2300)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8663)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```
How should I add this `v8__ArrayBuffer__WasDetached` symlink?

**Comment by waterbang** [comment]
Add the following function in v8/src/api/api.cc to solve the problem.
```c++
bool v8::ArrayBuffer::WasDetached() const {
  return Utils::OpenHandle(this)->was_detached();
}
```
