### ISSUE TITLE
build.rs failed download HTTP Error 404: Not Found (raspberry pi)

### ISSUE THREAD

**Issue by ChillerDragon** [denoland/rusty_v8#1223]
It tried to download a file that does not exist https://github.com/denoland/rusty_v8/releases/download/v0.71.0/librusty_v8_release_armv7-unknown-linux-gnueabihf.a

```
$ uname -a
Linux raspberrypi 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux
$ cargo install deno@1.33.1
[..]
   Compiling futures-executor v0.3.28
error: failed to run custom build command for `v8 v0.71.0`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installMcwvBq/release/build/v8-188355f7eaac56e3/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=.gn
  cargo:rerun-if-changed=BUILD.gn
  cargo:rerun-if-changed=src/binding.cc
  cargo:rerun-if-env-changed=CCACHE
  cargo:rerun-if-env-changed=CLANG_BASE_PATH
  cargo:rerun-if-env-changed=DENO_TRYBUILD
  cargo:rerun-if-env-changed=DOCS_RS
  cargo:rerun-if-env-changed=GN
  cargo:rerun-if-env-changed=GN_ARGS
  cargo:rerun-if-env-changed=HOST
  cargo:rerun-if-env-changed=NINJA
  cargo:rerun-if-env-changed=OUT_DIR
  cargo:rerun-if-env-changed=RUSTY_V8_ARCHIVE
  cargo:rerun-if-env-changed=RUSTY_V8_MIRROR
  cargo:rerun-if-env-changed=SCCACHE
  cargo:rerun-if-env-changed=V8_FORCE_DEBUG
  cargo:rerun-if-env-changed=V8_FROM_SOURCE
  cargo:rerun-if-env-changed=PYTHON
  cargo:rerun-if-env-changed=DISABLE_CLANG
  cargo:rerun-if-env-changed=EXTRA_GN_ARGS
  cargo:rerun-if-env-changed=NO_PRINT_GN_ARGS
  cargo:rustc-link-lib=static=rusty_v8
  download lockfile: "/tmp/cargo-installMcwvBq/release/build/lib_download.fslock"
  static lib URL: https://github.com/denoland/rusty_v8/releases/download/v0.71.0/librusty_v8_release_armv7-unknown-linux-gnueabihf.a
  cargo:rustc-link-search=/tmp/cargo-installMcwvBq/release/gn_out/obj
  Downloading https://github.com/denoland/rusty_v8/releases/download/v0.71.0/librusty_v8_release_armv7-unknown-linux-gnueabihf.a
  Downloading https://github.com/denoland/rusty_v8/releases/download/v0.71.0/librusty_v8_release_armv7-unknown-linux-gnueabihf.a...
  HTTP Error 404: Not Found
  Python downloader failed, trying with curl.

  --- stderr
  Traceback (most recent call last):
    File "/home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/v8-0.71.0/./tools/download_file.py", line 64, in <module>
      sys.exit(main())
    File "/home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/v8-0.71.0/./tools/download_file.py", line 59, in main
      DownloadUrl(args.url, f)
    File "/home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/v8-0.71.0/./tools/download_file.py", line 45, in DownloadUrl
      raise e
    File "/home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/v8-0.71.0/./tools/download_file.py", line 29, in DownloadUrl
      response = urlopen(url)
    File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
      return opener.open(url, data, timeout)
    File "/usr/lib/python3.9/urllib/request.py", line 523, in open
      response = meth(req, response)
    File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
      response = self.parent.error(
    File "/usr/lib/python3.9/urllib/request.py", line 561, in error
      return self._call_chain(*args)
    File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
      result = func(*args)
    File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
      raise HTTPError(req.full_url, code, msg, hdrs, fp)
  urllib.error.HTTPError: HTTP Error 404: Not Found
  thread 'main' panicked at 'assertion failed: status.success()', /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/v8-0.71.0/build.rs:431:3
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `deno v1.33.1`, intermediate artifacts can be found at `/tmp/cargo-installMcwvBq`
$ cargo install deno@1.32.5
   Compiling fslock v0.1.8
   Compiling v8 v0.68.0
error[E0425]: cannot find value `arch` in this scope
   --> /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/v8-0.68.0/build.rs:266:18
    |
266 |   format!("{os}-{arch}")
    |                  ^^^^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
error: could not compile `v8` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `deno v1.32.5`, intermediate artifacts can be found at `/tmp/cargo-installzVzBiB`
```

**Comment by ChillerDragon** [comment]
Oh this did the job my bad for not reading the readme :) 

```
V8_FROM_SOURCE=1 cargo install deno
```

Could maybe be hinted in the error message here

https://github.com/denoland/rusty_v8/blob/e0c8cb50e839622bfeca6a5691519d2f9c05bb73/build.rs#L431

**Comment by ChillerDragon** [comment]
Hm now I ran into this

```
$ V8_FROM_SOURCE=1 cargo install deno
[..]
   Compiling unicode-width v0.1.10
   Compiling futures-executor v0.3.28
error: failed to run custom build command for `v8 v0.71.0`

Caused by:
  process didn't exit successfully: `/tmp/cargo-instally81PEs/release/build/v8-188355f7eaac56e3/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=.gn
  cargo:rerun-if-changed=BUILD.gn
  cargo:rerun-if-changed=src/binding.cc
  cargo:rerun-if-env-changed=CCACHE
  cargo:rerun-if-env-changed=CLANG_BASE_PATH
  cargo:rerun-if-env-changed=DENO_TRYBUILD
  cargo:rerun-if-env-changed=DOCS_RS
  cargo:rerun-if-env-changed=GN
  cargo:rerun-if-env-changed=GN_ARGS
  cargo:rerun-if-env-changed=HOST
  cargo:rerun-if-env-changed=NINJA
  cargo:rerun-if-env-changed=OUT_DIR
  cargo:rerun-if-env-changed=RUSTY_V8_ARCHIVE
  cargo:rerun-if-env-changed=RUSTY_V8_MIRROR
  cargo:rerun-if-env-changed=SCCACHE
  cargo:rerun-if-env-changed=V8_FORCE_DEBUG
  cargo:rerun-if-env-changed=V8_FROM_SOURCE
  cargo:rerun-if-env-changed=PYTHON
  cargo:rerun-if-env-changed=DISABLE_CLANG
  cargo:rerun-if-env-changed=EXTRA_GN_ARGS
  cargo:rerun-if-env-changed=NO_PRINT_GN_ARGS
  cargo:rustc-link-lib=static=rusty_v8
  Downloading https://github.com/denoland/ninja_gn_binaries/archive/20221218.tar.gz... Done.

  --- stderr
  thread 'main' panicked at 'assertion failed: gn.exists()', /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/v8-0.71.0/build.rs:307:3
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `deno v1.33.1`, intermediate artifacts can be found at `/tmp/cargo-instally81PEs`
```
