### ISSUE TITLE
How to prevent downloads during build?

### ISSUE THREAD

**Issue by yurivict** [denoland/rusty_v8#1571]
See the failure log below.
freebsd14 isn't in the _HOST_OS_URL_MAP map, but downloads aren't allowed during build in package builders.

It attempts to download something from https://commondatastorage.googleapis.com/chromium-browser-clang

How to build v8 on FreeBSD without this download?
Is there a build-time option to disable it?

Version: 0.97.0
Encountered while building Deno.

Thank you,
Yuri

---log---
```
[v8 0.97.0] using Chromium's clang
[v8 0.97.0] clang_base_path (downloaded) /wrkdirs/usr/ports/www/deno/work/target/x86_64-unknown-freebsd/release/clang
[v8 0.97.0] Traceback (most recent call last):
[v8 0.97.0]   File "/wrkdirs/usr/ports/www/deno/work/deno-1.45.2/cargo-crates/v8-0.97.0/./tools/clang/scripts/update.py", line 386, in <module>
[v8 0.97.0]     sys.exit(main())
[v8 0.97.0]              ^^^^^^
[v8 0.97.0]   File "/wrkdirs/usr/ports/www/deno/work/deno-1.45.2/cargo-crates/v8-0.97.0/./tools/clang/scripts/update.py", line 382, in main
[v8 0.97.0]     return UpdatePackage(args.package, args.host_os, output_dir)
[v8 0.97.0]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[v8 0.97.0]   File "/wrkdirs/usr/ports/www/deno/work/deno-1.45.2/cargo-crates/v8-0.97.0/./tools/clang/scripts/update.py", line 289, in UpdatePackage
[v8 0.97.0]     DownloadAndUnpackPackage(package_file, dir, host_os)
[v8 0.97.0]   File "/wrkdirs/usr/ports/www/deno/work/deno-1.45.2/cargo-crates/v8-0.97.0/./tools/clang/scripts/update.py", line 197, in DownloadAndUnpackPackage
[v8 0.97.0]     cds_full_url = GetPlatformUrlPrefix(host_os) + cds_file
[v8 0.97.0]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[v8 0.97.0]   File "/wrkdirs/usr/ports/www/deno/work/deno-1.45.2/cargo-crates/v8-0.97.0/./tools/clang/scripts/update.py", line 189, in GetPlatformUrlPrefix
[v8 0.97.0]     return CDS_URL + '/' + _HOST_OS_URL_MAP[host_os] + '/'
[v8 0.97.0]                            ~~~~~~~~~~~~~~~~^^^^^^^^^
[v8 0.97.0] KeyError: 'freebsd14'
[v8 0.97.0] Traceback (most recent call last):
[v8 0.97.0]   File "/wrkdirs/usr/ports/www/deno/work/deno-1.45.2/cargo-crates/v8-0.97.0/./tools/clang/scripts/update.py", line 386, in <module>
[v8 0.97.0]     sys.exit(main())
[v8 0.97.0]              ^^^^^^
[v8 0.97.0]   File "/wrkdirs/usr/ports/www/deno/work/deno-1.45.2/cargo-crates/v8-0.97.0/./tools/clang/scripts/update.py", line 382, in main
[v8 0.97.0]     return UpdatePackage(args.package, args.host_os, output_dir)
[v8 0.97.0]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[v8 0.97.0]   File "/wrkdirs/usr/ports/www/deno/work/deno-1.45.2/cargo-crates/v8-0.97.0/./tools/clang/scripts/update.py", line 289, in UpdatePackage
[v8 0.97.0]     DownloadAndUnpackPackage(package_file, dir, host_os)
[v8 0.97.0]   File "/wrkdirs/usr/ports/www/deno/work/deno-1.45.2/cargo-crates/v8-0.97.0/./tools/clang/scripts/update.py", line 197, in DownloadAndUnpackPackage
[v8 0.97.0]     cds_full_url = GetPlatformUrlPrefix(host_os) + cds_file
[v8 0.97.0]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[v8 0.97.0]   File "/wrkdirs/usr/ports/www/deno/work/deno-1.45.2/cargo-crates/v8-0.97.0/./tools/clang/scripts/update.py", line 189, in GetPlatformUrlPrefix
[v8 0.97.0]     return CDS_URL + '/' + _HOST_OS_URL_MAP[host_os] + '/'
[v8 0.97.0]                            ~~~~~~~~~~~~~~~~^^^^^^^^^
[v8 0.97.0] KeyError: 'freebsd14'
[v8 0.97.0] thread 'main' panicked at /wrkdirs/usr/ports/www/deno/work/deno-1.45.2/cargo-crates/v8-0.97.0/build.rs:772:3:
[v8 0.97.0] assertion failed: Command::new(python()).arg("./tools/clang/scripts/update.py").arg("--output-dir").arg(&clang_base_path).status().unwrap().success()
[v8 0.97.0] stack backtrace:
[v8 0.97.0]    0: rust_begin_unwind
[v8 0.97.0]    1: core::panicking::panic_fmt
[v8 0.97.0]    2: core::panicking::panic
[v8 0.97.0]    3: build_script_build::build_v8
```

**Comment by devsnek** [comment]
You can set RUSTY_V8_ARCHIVE and RUSTY_V8_SRC_BINDING_PATH to files you manually downloaded from the associated release here: https://github.com/denoland/rusty_v8/releases
