### ISSUE TITLE
Build Failure on openSUSE

### ISSUE THREAD

**Issue by uncomfyhalomacro** [denoland/rusty_v8#1635]
**rusty_v8 version**: 129.0.0
**CC**: @avindra *openSUSE packager for rusty_v8*

Build environmental variables (some of this use rpmspec macros i.e. `%{_prefix}` refers to `/usr`)

```bash
# See https://github.com/denoland/rusty_v8/#build-v8-from-source
export V8_FROM_SOURCE=1
export CLANG_BASE_PATH=%{_prefix}
export GN_ARGS="clang_version=18 use_lld=false"
# Use Clang
export CC=clang CXX=clang++ AR=ar NM=nm
export CFLAGS="%{optflags}"
export CXXFLAGS="%{optflags}"
export RUST_BACKTRACE=full
%{__cargo} build %{__cargo_common_opts} --offline --release
```

<details><summary>Build Log</summary>

```
[   39s]   clang_base_path (system): /usr
[   39s]   The current directory is /home/abuild/rpmbuild/BUILD/rusty_v8-129.0.0
[   39s]   gn gen --root=/home/abuild/rpmbuild/BUILD/rusty_v8-129.0.0 /home/abuild/rpmbuild/BUILD/rusty_v8-129.0.0/target/release/gn_out
[   39s]   ERROR Can't load input file.
[   39s]   Unable to load:
[   39s]     /home/abuild/rpmbuild/BUILD/rusty_v8-129.0.0/build/config/BUILDCONFIG.gn
[   39s]   I also checked in the secondary tree for:
[   39s]     /home/abuild/rpmbuild/BUILD/rusty_v8-129.0.0/v8/build/config/BUILDCONFIG.gn
[   39s] 
[   39s]   --- stderr
[   39s]   thread 'main' panicked at build.rs:925:5:
[   39s]   assertion failed: Command::new(gn()).arg(format!("--root={}",
[   39s]                                                       dirs.root.display())).arg(format!("--script-executable={}",
[   39s]                                                   python())).arg("gen").arg(&gn_out_dir).arg("--ide=json").arg("--args=".to_owned()
[   39s]                                   +
[   39s]                                   &args).stdout(Stdio::inherit()).stderr(Stdio::inherit()).envs(env::vars()).status().expect("Could not run `gn`").success()
[   39s]   stack backtrace:
[   39s]      0:     0x55eb438a9d99 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h500272b372dbee0d
[   39s]      1:     0x55eb438c542b - core::fmt::write::h7d5f1514cee5490d
[   39s]      2:     0x55eb43892b69 - std::io::Write::write_fmt::h79aafa4f92dbd990
[   39s]      3:     0x55eb4388bdf6 - std::panicking::default_hook::{{closure}}::h3be5635ee55fbe2b
[   39s]      4:     0x55eb4388ba8f - std::panicking::default_hook::heb23de1613f25762
[   39s]      5:     0x55eb4388c368 - std::panicking::rust_panic_with_hook::hbb6bc5e5dcf363de
[   39s]      6:     0x55eb438aa2d3 - std::panicking::begin_panic_handler::{{closure}}::he8c824647d733ff6
[   39s]      7:     0x55eb438a9fa9 - std::sys::backtrace::__rust_end_short_backtrace::h9ef7b92757e5bdf6
[   39s]      8:     0x55eb4388bf34 - rust_begin_unwind
[   39s]      9:     0x55eb43237e03 - core::panicking::panic_fmt::hd3c9bc0ac2ebcfa1
[   39s]     10:     0x55eb43237e8c - core::panicking::panic::h2c807e0d9715b698
[   39s]     11:     0x55eb4324740f - build_script_build::maybe_gen::h145be4c53a275ac6
[   39s]                                  at /home/abuild/rpmbuild/BUILD/rusty_v8-129.0.0/build.rs:925:5
[   39s]     12:     0x55eb4323e84a - build_script_build::build_v8::hd731fe9d0d215799
[   39s]                                  at /home/abuild/rpmbuild/BUILD/rusty_v8-129.0.0/build.rs:315:16
[   39s]     13:     0x55eb4323ac5c - build_script_build::main::h14302a5f46189048
[   39s]                                  at /home/abuild/rpmbuild/BUILD/rusty_v8-129.0.0/build.rs:113:5
[   39s]     14:     0x55eb4324c83b - core::ops::function::FnOnce::call_once::h8a2336e837d58724
[   39s]                                  at /home/abuild/rpmbuild/BUILD/rustc-1.81.0-src/library/core/src/ops/function.rs:250:5
[   39s]     15:     0x55eb43255b3e - std::sys::backtrace::__rust_begin_short_backtrace::h16a620d78ec9455c
[   39s]                                  at /home/abuild/rpmbuild/BUILD/rustc-1.81.0-src/library/std/src/sys/backtrace.rs:152:18
[   39s]     16:     0x55eb43249051 - std::rt::lang_start::{{closure}}::h10f52f485e32f88c
[   39s]                                  at /home/abuild/rpmbuild/BUILD/rustc-1.81.0-src/library/std/src/rt.rs:162:18
[   39s]     17:     0x55eb4388b2a5 - std::rt::lang_start_internal::h1f4d7e49ff654c24
[   39s]     18:     0x55eb4324902a - std::rt::lang_start::h5789be0fac2ad62b
[   39s]                                  at /home/abuild/rpmbuild/BUILD/rustc-1.81.0-src/library/std/src/rt.rs:161:17
[   39s]     19:     0x55eb43248d0e - main
[   39s]     20:     0x7fbd6d82a340 - __libc_start_call_main
[   39s]     21:     0x7fbd6d82a409 - __libc_start_main@GLIBC_2.2.5
[   39s]     22:     0x55eb43238665 - _start
[   39s]                                  at /home/abuild/rpmbuild/BUILD/glibc-2.40/csu/../sysdeps/x86_64/start.S:115
[   39s]     23:                0x0 - <unknown>
```

</details>

**Comment by uncomfyhalomacro** [comment]
Woops. sorry for littering the issue tracker. it seems i have uploaded the wrong source tarball. :)
