### ISSUE TITLE
Building from source fails on macOS 11.0: "a bytes-like object is required, not 'str'"

### ISSUE THREAD

**Issue by kvark** [denoland/rusty_v8#504]
```
graphics35334:rusty_v8 dmalyshau$ V8_FROM_SOURCE=1 cargo build
   Compiling rusty_v8 v0.12.0 (/Users/dmalyshau/Code/rusty_v8)
The following warnings were emitted during compilation:

warning: Not using sccache or ccache

error: failed to run custom build command for `rusty_v8 v0.12.0 (/Users/dmalyshau/Code/rusty_v8)`

Caused by:
  process didn't exit successfully: `/Users/dmalyshau/Code/rusty_v8/target/debug/build/rusty_v8-d580b9fe1e113877/build-script-build` (exit code: 101)
  --- stdout
  Downloading https://github.com/denoland/ninja_gn_binaries/archive/20200827.tar.gz... Done.
  using Chromiums clang
  clang_base_path /Users/dmalyshau/Code/rusty_v8/target/debug/clang
  Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Mac/clang-llvmorg-12-init-4187-g33ce275f-1.tgz .......... Done.
  cargo:warning=Not using sccache or ccache
  The current directory is /Users/dmalyshau/Code/rusty_v8
  gn gen --root=/Users/dmalyshau/Code/rusty_v8 /Users/dmalyshau/Code/rusty_v8/target/debug/gn_out
  running: "/Users/dmalyshau/Code/rusty_v8/target/debug/ninja_gn_binaries-20200827/mac/gn" "--root=/Users/dmalyshau/Code/rusty_v8" "gen" "/Users/dmalyshau/Code/rusty_v8/target/debug/gn_out" "--args=is_debug=true use_custom_libcxx=false clang_base_path=\"/Users/dmalyshau/Code/rusty_v8/target/debug/clang\""
  ERROR at //build/config/mac/mac_sdk.gni:89:19: Script returned non-zero exit code.
  _mac_sdk_result = exec_script(script_name, sdk_info_args, "scope")
                    ^----------
  Current dir: /Users/dmalyshau/Code/rusty_v8/target/debug/gn_out/
  Command: python /Users/dmalyshau/Code/rusty_v8/build/config/mac/sdk_info.py macosx
  Returned 1.
  stderr:

  Traceback (most recent call last):
    File "/Users/dmalyshau/Code/rusty_v8/build/config/mac/sdk_info.py", line 152, in <module>
      FillXcodeVersion(settings, args.developer_dir)
    File "/Users/dmalyshau/Code/rusty_v8/build/config/mac/sdk_info.py", line 65, in FillXcodeVersion
      settings['xcode_version'] = FormatVersion(lines[0].split()[-1])
    File "/Users/dmalyshau/Code/rusty_v8/build/config/mac/sdk_info.py", line 49, in FormatVersion
      major, minor, patch = SplitVersion(version)
    File "/Users/dmalyshau/Code/rusty_v8/build/config/mac/sdk_info.py", line 36, in SplitVersion
      version = version.split('.')
  TypeError: a bytes-like object is required, not 'str'

  See //build/toolchain/mac/BUILD.gn:15:1: whence it was imported.
  import("//build/config/mac/mac_sdk.gni")
  ^--------------------------------------
  See //BUILD.gn:3:1: which caused the file to be included.
  static_library("rusty_v8") {
  ^---------------------------

  --- stderr
  thread 'main' panicked at '
  command did not execute successfully, got: exit code: 1

  build script failed, must exit now', /Users/dmalyshau/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo_gn-0.0.15/src/lib.rs:203:3
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by bnoordhuis** [comment]
It looks like python is python3 on your system but V8's build scripts expect python2.
